vich_uploader:
    db_driver: orm

    mappings:
        images:
            uri_prefix: /assets/pictures
            upload_destination: '%kernel.project_dir%/public/asset/pictures'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer